### ISSUE TITLE
midi_labelの13番と14番が逆の可能性がある

### ISSUE THREAD

**Issue by Hiroshiba** [mmorise/kiritan_singing#1]
midi_labelの13番と14番が逆の可能性があります。

図。上から、13番のMIDI、13番のwav、14番のwav。
![image](https://user-images.githubusercontent.com/4987327/69404834-9d38c480-0d41-11ea-9438-8be3e28441cf.png)

**Comment by mmorise** [comment]
ありがとうございます．こちら，MIDIラベル担当者にチェックしてもらい，ご指摘のとおりであることが確認できました．

**Comment by Hiroshiba** [comment]
ありがとうございます！
