### ISSUE TITLE
midi_labelの06版の後半が欠けている可能性がある

### ISSUE THREAD

**Issue by Hiroshiba** [mmorise/kiritan_singing#2]
midi_labelの6番の後半が欠けている可能性があります。

図です。上からmidi_labelの6番、mono_labelの6番、wavの6番です。
![image](https://user-images.githubusercontent.com/4987327/69415207-8c934900-0d57-11ea-9d6c-b70c26f21660.png)

**Comment by mmorise** [comment]
こちらもご指摘のとおりでしたので，MIDIラベル担当者に修正してもらっております．修正完了後アップロードしますので，しばらくお時間をください．

**Comment by mmorise** [comment]
こちら，新しいラベルデータをアップロード致しました．
よろしくお願いいたします．

**Comment by Hiroshiba** [comment]
ありがとうございます！
