### ISSUE TITLE
06.lab: 616-617行目: 音素ラベルに開始時間の重複があります

### ISSUE THREAD

**Issue by r9y9** [mmorise/kiritan_singing#4]
https://github.com/mmorise/kiritan_singing/blob/c21c1fa068fb54f8157bb4a04ce991a6773e8f40/mono_label/06.lab#L616-L617

手作業による誤りではないかと考えられます。616行目が正しいとすれば、617行目は以下のようになると思いますが、ご確認いただけますでしょうか？

```diff
617c617
< 290.3510229 290.4590797 sh
---
> 290.4108697 290.4590797 sh
```

**Comment by mmorise** [comment]
こちら，ご指摘のとおりです．修正致します．

**Comment by r9y9** [comment]
masterに修正がコミットされていることに気づきました。ご対応ありがとうございます
