### ISSUE TITLE
08.xml: 冒頭部分の歌詞情報が楽譜から抜け落ちている？

### ISSUE THREAD

**Issue by r9y9** [mmorise/kiritan_singing#5]
![Screenshot from 2020-04-05 21-13-09](https://user-images.githubusercontent.com/1220272/78486915-4a0c5f00-7782-11ea-9727-1d5439b7cee7.png)

.labファイルでいうところの下記相当です：
https://github.com/mmorise/kiritan_singing/blob/c21c1fa068fb54f8157bb4a04ce991a6773e8f40/mono_label/08.lab#L3-L136

Sinsyを用いてmusicxmlからラベルファイルを生成したころ、冒頭部分がかけてしまっていたため、おそらくmusicxmlファイルに不足しているデータがあるのだと思います。
私がmusicxmlに詳しくないため、musicxmlのパースに失敗しているのか、そもそもデータが存在しないのか確信がないのですが、お時間があれば調べてみていただけると幸いです。

**Comment by mmorise** [comment]
はい，こちらは，トップにも書かせていただいておりますが，08の前半は担当者により「採譜不可能」という意見があったので，音素ラベルはあるけどmusicXML（MIDI）が存在しないという状況になっております．ご利用の際は，該当する音素ラベルを除去してpauの時間を増やすような調整が必要になります．せっかくラベル付けしたので残していましたが，譜面との整合性を考えると残した方が良いかもしれません．

**Comment by r9y9** [comment]
あ、なるほど、確認不足でした…。利用する際には、該当する音素ラベルを削除して使用するようにします。回答ありがとうございます
